### ISSUE TITLE
Rails behave weird and copper rails crash game (Farmer's Delight Refabricated)

### ISSUE THREAD

**Issue by Lucky-56** [FXCourel/Copper-Rails#4] opened 2024-08-28 19:01 UTC
Rails place as ghost blocks, don't connect around corners or slopes and copper rails seem to crash game on oxidization
incompatability with [Farmer's Delight Refabricated](https://modrinth.com/mod/farmers-delight-refabricated)

---

**Minecraft ver:** 1.21.1
**Fabric ver:** 0.16.3
**Mod ver:** 1.0.3

**Farmer's Delight ver:** 2.1.6

---

**Log:** https://mclo.gs/1I9Dwv9

**Comment by FXCourel** [comment] 2024-08-28 20:12
I confirm this issue, but I dont know what causes it, especially because features of CopperRails and Farmer's delight don't intersect.

Might be caused by conflicts with the portlib mod (dependancy of farmer's delight which helps port forge mods to fabric, and deploys mixins helpers). Strangely, the game loads a 1.21 version of this mod but it has no version after 1.20.4...

Anyway, if you doesnt your game to crash, use waxed copper rails (crashes are caused by oxidation ticking) or disable random ticking, and I won't fix this issue that I can't know the reason, sorry :(

**Comment by FXCourel** [comment] 2024-08-28 20:32
Found a potential solution, will see if I have time tomorrow (not sure)

**Closed** 2024-08-29 10:22 UTC
